dataset:
  augmentations:
    brightness_contrast: 0.2
    enabled: true
    horizontal_flip: 0.5
    noise_probability: 0.3
    rotation_limit: 15
  balance_strategy: oversample_positive
  cache_images: false
  class_mapping:
    0: MILCO
    1: NOMBO
  data_path: ./Data/
  enhance_sonar: true
  image_size:
  - 512
  - 512
  normalize: true
  splits:
    stratified:
      random_state: 42
      test_ratio: 0.15
      train_ratio: 0.7
      val_ratio: 0.15
training:
  batch_size: 16
  num_workers: 4
