dataset:
  augmentations:
    brightness_contrast: 0.2
    contrast_limit: 0.2         # Moderate contrast changes
    enabled: true
    horizontal_flip: 0.4
    vertical_flip: 0.1   
    noise_probability: 0.1
    rotation_limit: 15
  balance_strategy: oversample_positive
  cache_images: false
  class_mapping:
    0: MILCO
    1: NOMBO
  data_path: ./Data/
  enhance_sonar: true
  clahe_settings:
    clip_limit: 2.0
    tile_grid_size: [4, 4]  # coarse grainned
  image_size:
  - 512
  - 512
  normalize: true
  splits:
    stratified:
      random_state: 42
      test_ratio: 0.15
      train_ratio: 0.7
      val_ratio: 0.15
training:
  batch_size: 16
  num_workers: 4
